#ifndef LIST_ERROR_TYPES_H_
#define LIST_ERROR_TYPES_H_

typedef enum {
    LIST_ERROR_NO,
    LIST_ALLOCATION_FAILED,
    LIST_REALLOCATION_FAILED,
    LIST_WRONG_SPECIFIED_CAPACITY,
    LIST_ERROR_OPENING_FILE,
    LIST_NULL_POINTER,
    LIST_INVALID_INDEX,
    LIST_NO_FREE_SPACE
} ListErrorType;

typedef enum {
    VERIFY_SUCCESS,
    VERIFY_FAKE_ELEMENT_NEXT_ERROR,
    VERIFY_FAKE_ELEMENT_PREV_ERROR,
    VERIFY_TAIL_NEXT_ERROR,
    VERIFY_HEAD_PREV_ERROR,
    VERIFY_CAPACITY_EXCEEDED,
    VERIFY_INVALID_INDEX,
    VERIFY_BIDIRECTIONAL_LINK_ERROR,
    VERIFY_COUNT_MISMATCH,
    VERIFY_EMPTY_LIST_LINKS_ERROR,
    VERIFY_CYCLE_DETECTED
} VerifyResult;
#endif //LIST_ERROR_TYPES_H_
