#ifndef LIST_ERROR_TYPES_H_
#define LIST_ERROR_TYPES_H_

typedef enum {
    LIST_ERROR_NO,
    LIST_ALLOCATION_FAILED,
    LIST_REALLOCATION_FAILED,
    LIST_WRONG_SPECIFIED_CAPACITY,
    LIST_ERROR_OPENING_FILE,
    LIST_NULL_POINTER,
    LIST_INVALID_INDEX,
    LIST_NO_FREE_SPACE
} ListErrorType;

#endif //LIST_ERROR_TYPES_H_
